version: '3.1'

services:

  dbmongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: jbermejo
      MONGO_INITDB_ROOT_PASSWORD: miclavesecreta